services:
  tgbot:
    build:
      context: .
      dockerfile: tgbot/Dockerfile
    env_file:
      - .env
    depends_on:
      - api
    command: python -m tgbot.bot

  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
#  postgres:
#    image: postgres:15
#    restart: always
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    networks:
#      - botnet
#
#  redis:
#    image: redis:7
#    restart: always
#    volumes:
#      - redis_data:/data
#    networks:
#      - botnet
#
#  nginx:
#    image: nginx:1.25
#    restart: always
#    depends_on:
#      - api
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/ssl:/etc/nginx/ssl
#    networks:
#      - botnet
#
#volumes:
#  postgres_data:
#  redis_data: