services:
  tgbot:
    build:
      context: .
      dockerfile: src/tgbot/Dockerfile
    env_file:
      - .env
    depends_on:
      - api
      - qdrant
    command: python -m src.tgbot.bot
    develop:
      watch:
       - path: src/
         action: sync+restart
         target: src/
#    networks:
#      - botnet

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/app/data
#    networks:
#      - botnet
    
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - "6333"
      - "6334"
    volumes:
      - qdrant_storage:/qdrant/storage
#    networks:
#      - botnet
#  postgres:
#    image: postgres:15
#    restart: always
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    networks:
#      - botnet
#
#  redis:
#    image: redis:7
#    restart: always
#    volumes:
#      - redis_data:/data
#    networks:
#      - botnet
#
#  nginx:
#    image: nginx:1.25
#    restart: always
#    depends_on:
#      - api
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/ssl:/etc/nginx/ssl
#    networks:
#      - botnet
#
volumes:
  qdrant_storage:

#networks:
#  botnet:
#  postgres_data:
#  redis_data: