"""add is_active column to message_blobs

Revision ID: 03484f5cf53a
Revises: 28353e641c3b
Create Date: 2025-09-08 16:58:06.063222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03484f5cf53a'
down_revision: Union[str, None] = '28353e641c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_blobs', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_blobs', 'is_active')
    # ### end Alembic commands ###
