"""removed chat model and put messages to user model

Revision ID: 28353e641c3b
Revises: dcf7c2bb6cfd
Create Date: 2025-09-06 17:56:40.999752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28353e641c3b'
down_revision: Union[str, None] = 'dcf7c2bb6cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_blobs_chat_id_fkey', 'message_blobs', type_='foreignkey')
    op.drop_constraint('users_chat_id_fkey', 'users', type_='foreignkey')
    op.drop_column('message_blobs', 'chat_id')
    op.add_column('message_blobs', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'message_blobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('chats')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_chat_id_fkey', 'users', 'chats', ['chat_id'], ['id'])
    op.add_column('message_blobs', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message_blobs', type_='foreignkey')
    op.create_foreign_key('message_blobs_chat_id_fkey', 'message_blobs', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('message_blobs', 'user_id')
    op.create_table('chats',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chats_pkey')
    )
    # ### end Alembic commands ###
